export default ['precision mediump float;',
'uniform vec2 resolution;',
'uniform sampler2D texture;',
'void main() {',
  'vec2 uv = gl_FragCoord.xy / resolution;',
  'uv.y = 1.0 - uv.y;',
  'vec4 col = texture2D(texture, vec2(uv.x * 0.5 + 0.5, uv.y));',
  'float alpha = texture2D(texture, vec2(uv.x * 0.5, uv.y)).x;',
  'if (alpha < 0.01){ discard; }',
  'gl_FragColor = vec4(col.rgb, alpha);',
  // 'gl_FragColor = vec4( col.rgb, alpha );',
'}'].join('\n');
